Support untitled buffer
prabirshrestha/vim-lsp pull request #1152
Opened 2021-04-27 06:00 UTC by mattn

Fixed #658

2021-04-27 08:13 UTC, rhysd requested changes

2021-04-27 08:13 UTC, rhysd commented on plugin/lsp.vim
> +let g:lsp_untitled_buffer_enabled = get(g:, 'lsp_untitled_buffer_enabled', 1)
Can we have documentation for this variable?

2021-04-27 08:13 UTC, rhysd commented on autoload/lsp/utils.vim
> +        let l:nr = bufnr(a:0 > 0 ? '#' . a:1 : '%')
`#` means alternate buffer in parameter of `bufnr()` or `bufname()`. So `#{number}` is not valid format here.

```suggestion
        let l:nr = a:0 > 0 ? a:1 : bufnr('%')
```

would be correct

2021-04-27 08:35 UTC, rhysd commented
@mattn Just clarification: When opening a new file with file extension, `s:on_text_document_did_open()` will be called twice on `BufNewFile` and `FileType`. Is it ok? For example, `lsp_buffer_enabled` might be notified twice.

2021-04-27 09:43 UTC, mattn commented
As far as I looked the part of codes, it seems okay and lsp_buffer_enabled is not triggered twice. But we might need to stop unused servers. (TODO)

2021-04-27 19:43 UTC, prabirshrestha commented
what happens if the file is saved with a proper name?

should we unload the unnamed buffer and then load the proper files?

2021-05-01 15:44 UTC, mattn commented
When the file is saved, it mean the URI is changed as same as titled file is renamed.

2021-05-10 06:47 UTC, rhysd approved these changes
Code changes look good.

> As far as I looked the part of codes, it seems okay and lsp_buffer_enabled is not triggered twice. But we might need to stop unused servers. (TODO)

Please remember to confirm this before merging this.

2021-09-09 17:38 UTC, prabirshrestha commented
LGTM

2021-09-27 09:22 UTC, mattn commented
I tried this PR for a few weeks. I had no problems with clangd and some other language servers. Thanks.

2021-09-27 09:22 UTC, merged