Convert lowercase drive letters to uppercase
prabirshrestha/vim-lsp pull request #953
Opened 2020-12-19 22:47 UTC by bamchoh

I faced a problem that error diagnostics message does not shown in golang source code. In a result of my investigation, this problem occurs when I change the current directory with lowercase driveletter like `cd c:\dev\go\test001`. When `cd C:\dev\go\test001` is no problem. To avoid this problem, we need to convert driver letter to uppercase in lsp#utils#path_to_uri function.

2020-12-22 17:33 UTC, prabirshrestha commented
Can you add tests for utils.

Path codepath is quite fragile so having unit tests would help with regressions.

2020-12-22 19:01 UTC, bamchoh commented
Thank you for your advice. I added a test.

2020-12-23 19:01 UTC, prabirshrestha commented
I need to think about this since it can cause lot of issues. If we are only having issues with diagnostics can we instead fix the diagnostics? 

https://github.com/prabirshrestha/vim-lsp/blob/b316729ef59b586042b9c087b8e869ff331fdfd2/autoload/lsp/ui/vim/diagnostics.vim#L247-L261

There are tools like [driveup](https://www.npmjs.com/package/driveup) which forces uppercase drive letter but I don't expect them this to be used all the time.

2020-12-24 10:15 UTC, prabirshrestha commented
some more discussions about this at https://github.com/microsoft/language-server-protocol/pull/1019

2020-12-24 12:53 UTC, bamchoh commented
@prabirshrestha Thank you for explanation why we should not modify utils.vim for lowercase driver letter. I understood it.
Also I understood that you had already code for lowercase driver letter because a typescript language server treat driver letter as lowercase.
On the other hands, it seems that gopls treat drive letter as uppercase internally. 
https://github.com/golang/tools/blob/bce87a7896ccdbaeca70664555ea4d0e6cb1444b/internal/span/uri.go#L141
Hence, I faced this issue.
To treat driver letter for both cases properly, I revise diagnostics.vim so that modify the uri which is returned from the server on "textDocument/publishDiagnostics" to lowercase everytime.

I'm sorry that I did not add test codes for this modification because I don't know how to add them.

2020-12-24 20:24 UTC, prabirshrestha commented
Here is what i would do.

* Create a function that normalizes a uri in utils so it can be tested independently. Normalized function should be a noop in non-windows environment.
* Then in diagnostics.vim call the normalized function

Having the normalized function would allow us reuse it for other features.

To run tests I would add a `vim-themis` as a vim plugin.   `Plug 'thinca/vim-themis'` then add `vim-themis\bin` in your path. Then go to vim-lsp plugin folder and type `themis.bat`. It should run all the tests. if you want to only run your tests you can use `--target pattern` i.e. `themis.bat --target uri`. Someday I should most likely have `doc/vim-lsp-dev.txt`.

2020-12-25 18:34 UTC, prabirshrestha commented on autoload/lsp/utils.vim
> +    function! lsp#utils#normalize_uri(uri) abort
add a comment to https://github.com/microsoft/language-server-protocol/pull/1019 for future reference.

2020-12-25 18:35 UTC, prabirshrestha commented
Looking good. Added a nit comment. Can you fix it while I try this on my windows machine to see if it works on typescript language server.

2020-12-25 18:55 UTC, prabirshrestha requested changes
I tried it on windows with rust-analzyer and typescript-langauge-server and works.

I have added few more comments before I merge.

Thanks for the PR.

2020-12-25 18:55 UTC, prabirshrestha commented on autoload/lsp/ui/vim/diagnostics.vim
>      if s:is_win
`s:is_win` check not required now since `normalize_uri` will handle it.

2020-12-25 19:02 UTC, bamchoh commented
Thank you for your code review. I added a comment. But I'm not sure whether or not it is correct English because I'm not native English speaker.

2020-12-25 19:05 UTC, prabirshrestha commented on autoload/lsp/utils.vim
> +        " Now, it is discussing about normalization of uri.
Change tot the following.

```vim
" Refer to https://github.com/microsoft/language-server-protocol/pull/1019 on normalization of urls.
" TODO: after the discussion is settled, modify this function. 
```

2020-12-25 19:06 UTC, prabirshrestha commented
No worries. I added comment for the comment. Then should be good to merge.

2020-12-25 19:09 UTC, prabirshrestha approved these changes

2020-12-25 19:10 UTC, bamchoh commented
Thank you very much for your kindly review. I revised a comment as per as your suggestion.

2020-12-25 19:11 UTC, merged

2020-12-25 19:12 UTC, prabirshrestha commented
Merged. Thanks for the PR and your patience.